### ISSUE TITLE
rtmidi error

### ISSUE THREAD

**Issue by Rhoumi** [Bubobubobubobubo/sardine#172]
what's going on with sardine on my computer, every thing was working and now it's pure madness.

i'm lost....

 i've got this error and i can't acces to sardine-config midi,
 
helpme ....
                                             My last wishes would be to be able to play some funky patterns on _sardine_..............

```
ALSA lib conf.c:3558:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so (/usr/lib64/alsa-lib/libasound_module_conf_pulse.so: libasound_module_conf_pulse.so: cannot open shared object file: No such file or directory)
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default
Traceback (most recent call last):
  File "src/_rtmidi.pyx", line 815, in rtmidi._rtmidi.MidiIn.__cinit__
RuntimeError: MidiInAlsa::initialize: error creating ALSA sequencer client object.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ralt144mi/Sardine/fishery/console.py", line 73, in runcode
    return future.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/ralt144mi/Sardine/fishery/console.py", line 46, in _callback
    coro = func()
  File "<console>", line 1, in <module>
  File "/home/ralt144mi/.local/lib/python3.10/site-packages/sardine/run.py", line 55, in <module>
    midi = MidiHandler(port_name=str(config.midi))
  File "/home/ralt144mi/.local/lib/python3.10/site-packages/sardine/handlers/midi.py", line 26, in __init__
    self._available_ports = mido.get_output_names()
  File "/home/ralt144mi/.local/lib/python3.10/site-packages/mido/backends/backend.py", line 175, in get_output_names
    devices = self._get_devices(**self._add_api(kwargs))
  File "/home/ralt144mi/.local/lib/python3.10/site-packages/mido/backends/backend.py", line 163, in _get_devices
    return self.module.get_devices(**self._add_api(kwargs))
  File "/home/ralt144mi/.local/lib/python3.10/site-packages/mido/backends/rtmidi.py", line 52, in get_devices
    mi = rtmidi.MidiIn(rtapi=rtapi)
  File "src/_rtmidi.pyx", line 817, in rtmidi._rtmidi.MidiIn.__cinit__
rtmidi._rtmidi.SystemError: MidiInAlsa::initialize: error creating ALSA sequencer client object.
```

**Comment by Rhoumi** [comment]
Sometimes i get this error too :
(i think it's because of different/multiple version of python/pip/rtmidi... but don't know what to do) 
```
Traceback (most recent call last):
  File "/home/ralt144mi/Sardine/fishery/console.py", line 73, in runcode
    return future.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/ralt144mi/Sardine/fishery/console.py", line 46, in _callback
    coro = func()
  File "<console>", line 1, in <module>
  File "/home/ralt144mi/Sardine/sardine/run.py", line 68, in <module>
    midi = MidiHandler(port_name=str(config.midi))
  File "/home/ralt144mi/Sardine/sardine/handlers/midi.py", line 25, in __init__
    self._available_ports = mido.get_output_names()
  File "/home/ralt144mi/.local/lib/python3.10/site-packages/mido/backends/backend.py", line 175, in get_output_names
    devices = self._get_devices(**self._add_api(kwargs))
  File "/home/ralt144mi/.local/lib/python3.10/site-packages/mido/backends/backend.py", line 163, in _get_devices
    return self.module.get_devices(**self._add_api(kwargs))
  File "/home/ralt144mi/.local/lib/python3.10/site-packages/mido/backends/rtmidi.py", line 50, in get_devices
    rtapi = _get_api_id(api)
  File "/home/ralt144mi/.local/lib/python3.10/site-packages/mido/backends/rtmidi.py", line 34, in _get_api_id
    return rtmidi.API_UNSPECIFIED
AttributeError: module 'rtmidi' has no attribute 'API_UNSPECIFIED'
```

**Comment by Rhoumi** [comment]
Update and closing,
this was not a sardine related error, 
i had to copy the ` /usr/lib/alsa-lib/` dir into `usr/lib/x86_64-linux-gnu/alsa-lib` and `usr/lib64/alsa-lib`

**Comment by joenio** [comment]
I had the same issue.

I have fixed it installing Debian package for `python-rtmidi` and re-installing sardine without the argument `--find-links https://thegamecracks.github.io/python-rtmidi-wheels/` as below:

```sh
sudo apt install python3-rtmidi
python3 -m pip install sardine-system
```

- ps(1).: my environment is a Debian testing.
- ps(2).: I'm not sure if the step `sudo apt install python3-rtmidi` is needed.
