### ISSUE TITLE
can't install - ubuntu 23.04

### ISSUE THREAD

**Issue by ndr0n** [Bubobubobubobubo/sardine#221]
I get this error when trying to install on ubuntu 23.04

(audio) esquilo@toplap:~/Downloads/sardine$ python -m pip install --find-links https://thegamecracks.github.io/python-rtmidi-wheels/ sardine-system . 
Looking in links: https://thegamecracks.github.io/python-rtmidi-wheels/
Processing /home/esquilo/Downloads/sardine
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting sardine-system
  Using cached sardine_system-0.2.1-py3-none-any.whl (100 kB)
Collecting LinkPython-extern>=1.0.2
  Using cached LinkPython_extern-1.0.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (209 kB)
Collecting ziffers>=0.0.1
  Using cached ziffers-0.0.1-py3-none-any.whl (41 kB)
Collecting uvloop>=0.16
  Using cached uvloop-0.17.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.1 MB)
Collecting inquirerpy>=0.3.4
  Using cached InquirerPy-0.3.4-py3-none-any.whl (67 kB)
Collecting exceptiongroup>=1.0.4
  Using cached exceptiongroup-1.1.1-py3-none-any.whl (14 kB)
Collecting osc4py3>=1.0.8
  Using cached osc4py3-1.0.8-py3-none-any.whl
Collecting Flask>=2.2.2
  Using cached Flask-2.3.2-py3-none-any.whl (96 kB)
Collecting appdirs>=1.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting Flask-Cors>=3.0
  Using cached Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting Click>=8.1.3
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting lark>=1.1
  Using cached lark-1.1.5-py3-none-any.whl (107 kB)
Collecting python-rtmidi>=1.4.9
  Using cached python_rtmidi-1.5.0-cp310-cp310-manylinux_2_28_x86_64.whl (603 kB)
Collecting easing-functions>=1.0.4
  Using cached easing_functions-1.0.4-py3-none-any.whl (15 kB)
Collecting pygtail>=0.14.0
  Using cached pygtail-0.14.0-py3-none-any.whl (14 kB)
Collecting rich>=12.5
  Using cached rich-13.3.5-py3-none-any.whl (238 kB)
Collecting Flask-SocketIO>=5.3.2
  Using cached Flask_SocketIO-5.3.4-py3-none-any.whl (17 kB)
Collecting mido>=1.2
  Using cached mido-1.2.10-py2.py3-none-any.whl (51 kB)
Collecting psutil>=5.9
  Using cached psutil-5.9.5-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (282 kB)
Collecting parsimonious>=0.10.0
  Using cached parsimonious-0.10.0-py3-none-any.whl (48 kB)
Collecting Jinja2>=3.1.2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting itsdangerous>=2.1.2
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting blinker>=1.6.2
  Using cached blinker-1.6.2-py3-none-any.whl (13 kB)
Collecting Werkzeug>=2.3.3
  Using cached Werkzeug-2.3.4-py3-none-any.whl (242 kB)
Collecting Six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting python-socketio>=5.0.2
  Using cached python_socketio-5.8.0-py3-none-any.whl (56 kB)
Collecting pfzy<0.4.0,>=0.3.1
  Using cached pfzy-0.3.4-py3-none-any.whl (8.5 kB)
Collecting prompt-toolkit<4.0.0,>=3.0.1
  Using cached prompt_toolkit-3.0.38-py3-none-any.whl (385 kB)
Collecting regex>=2022.3.15
  Using cached regex-2023.5.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (769 kB)
Collecting markdown-it-py<3.0.0,>=2.2.0
  Using cached markdown_it_py-2.2.0-py3-none-any.whl (84 kB)
Collecting pygments<3.0.0,>=2.13.0
  Using cached Pygments-2.15.1-py3-none-any.whl (1.1 MB)
Collecting pytest>=7.2.1
  Using cached pytest-7.3.1-py3-none-any.whl (320 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting mdurl~=0.1
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)
Collecting packaging
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting iniconfig
  Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting tomli>=1.0.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting python-engineio>=4.3.0
  Using cached python_engineio-4.4.1-py3-none-any.whl (53 kB)
Collecting bidict>=0.21.0
  Using cached bidict-0.22.1-py3-none-any.whl (35 kB)
Building wheels for collected packages: sardine-system
  Building wheel for sardine-system (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for sardine-system (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [95 lines of output]
      /tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:66: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        config = read_configuration(filepath, True, ignore_option_errors, dist)
      running bdist_wheel
      running build
      running build_py
      running build_npm
      yarn install v1.22.19
      warning package.json: No license field
      warning client@0.0.1: No license field
      [1/4] Resolving packages...
      success Already up-to-date.
      Done in 0.19s.
      yarn run v1.22.19
      warning package.json: No license field
      $ vite build
      
      vite v4.0.4 building SSR bundle for production...
      transforming...
      
      src/routes/+layout.svelte
      `<slot />` missing — inner content will not be rendered
      11:39:30 PM [vite-plugin-svelte] /src/lib/components/Header.svelte:26:9 A11y: '' is not a valid href attribute
      24:         <div class="dropdown-content">
      25:           {#each Object.entries(tutorialText) as [title, content]}
      26:             <a href="" on:click|preventDefault={() => dispatch('loadtutorial', { text: content })}>
                         ^
      27:               {title}
      28:             </a>
      ✓ 72 modules transformed.
      11:39:30 PM [vite-plugin-svelte] ssr compile done.
      package             files     time     avg
      client                 17    0.30s  17.8ms
      @sveltejs/kit           1   29.3ms  29.3ms
      [vite]: Rollup failed to resolve import "sveltestrap" from "/home/esquilo/Downloads/sardine/sardine/client/src/lib/components/Header.svelte".
      This is most likely unintended because it can break your application at runtime.
      If you do want to externalize this module explicitly add it to
      `build.rollupOptions.external`
      error during build:
      Error: [vite]: Rollup failed to resolve import "sveltestrap" from "/home/esquilo/Downloads/sardine/sardine/client/src/lib/components/Header.svelte".
      This is most likely unintended because it can break your application at runtime.
      If you do want to externalize this module explicitly add it to
      `build.rollupOptions.external`
          at onRollupWarning (file:///home/esquilo/Downloads/sardine/sardine/client/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44636:19)
          at onwarn (file:///home/esquilo/Downloads/sardine/sardine/client/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44407:13)
          at Object.onwarn (file:///home/esquilo/Downloads/sardine/sardine/client/node_modules/rollup/dist/es/shared/rollup.js:24518:13)
          at ModuleLoader.handleInvalidResolvedId (file:///home/esquilo/Downloads/sardine/sardine/client/node_modules/rollup/dist/es/shared/rollup.js:23199:26)
          at file:///home/esquilo/Downloads/sardine/sardine/client/node_modules/rollup/dist/es/shared/rollup.js:23159:26
      error Command failed with exit code 1.
      info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
      Traceback (most recent call last):
        File "/home/esquilo/miniconda3/envs/audio/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/esquilo/miniconda3/envs/audio/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/esquilo/miniconda3/envs/audio/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 134, in <module>
        File "/tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-2ror5wf_/normal/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-2ror5wf_/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 59, in run
        File "/home/esquilo/miniconda3/envs/audio/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '"/home/esquilo/.nvm/versions/node/v20.2.0/bin/npx" yarn run build' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sardine-system
Failed to build sardine-system
ERROR: Could not build wheels for sardine-system, which is required to install pyproject.toml-based projects

**Comment by Bubobubobubobubo** [comment]
Oops, my bad! I forgot to clean some of my earlier experiments with Svelte. Can you try to clone the project again? This time it should be alright!
